name: Render documents and upload

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - main
  schedule:
    - cron: '45 4 * * *'
jobs:
  autoscrape:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     # Load repo and install R
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-


        # Set-up R packages
      - name: Install libraries
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages('rmarkdown')
          install.packages('tidyverse')
          install.packages('flexdashboard')
          install.packages('plotly')
 
 
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
          # Render index.Rmd using rmarkdown
      - name: render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "html_document")'

 # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        if: ${{ github.event_name == 'schedule' }}
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin develop
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
