name: render readme

# Controls when the action will run
on:
  push:
    branches: develop

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown","tidyverse","flexdashboard","plotly"))'

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'

    - name: commit rendered README
      run: |
        git add README.md man/figures/README-*
        git commit -m "index.Rmd" || echo "No changes to commit"
        git push origin develop || echo "No changes to commit"
